### ISSUE TITLE
Error trying to connect socket

### ISSUE THREAD

**Issue by Yuvraj-021** [goodydeves/PhishBuster#1]
Hello sir , 
       I'm facing the issue of Error trying to connect socket while running the url feature extraction from dataset file. can you help with it please

**Comment by goodycy3** [comment]
Alright pls send me a screenshot let me take a look..

**Comment by Yuvraj-021** [comment]
![error ss](https://user-images.githubusercontent.com/69747262/148921670-938fdb42-6106-4d33-ac2e-417e2313075f.png)

**Comment by Yuvraj-021** [comment]
![error ss2](https://user-images.githubusercontent.com/69747262/148921931-09fe4c28-1205-4199-95de-1a2edbb6fe96.png)

**Comment by goodycy3** [comment]
Thanks, I'll check it out.
Will get back to you tomorrow ....on it
Thanks

**Comment by Yuvraj-021** [comment]
Ok thanks!

**Comment by goodycy3** [comment]
Hi Yuvraj,
Kind look for the python file URLFeatureExtraction.py like the image below,
and run it, or better still try using pycharm or vs code. hope it works
Thanks
[image: image.png]

**Comment by Yuvraj-021** [comment]
Hi Goodydeves, 
thanks for your response, I had tried running it on vscode as well as pycharm but its giving me the same error

**Comment by Yuvraj-021** [comment]
I found out the cause , it was happening because we were detecting 5000 samples and due to that the socket was closing if we try to give less no in it it runs fine. Thankyou for your support!

**Comment by goodycy3** [comment]
Glad to hear that
Kindly commit so that the solution could help others as.
Thanks

So sorry for late reply
